# Branches that trigger a build on commit
trigger:
- main
- main-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
- main
- main-vs-deps
- release/*
- features/*
- demos/*

# Windows Build and Test Jobs
jobs:
- template: eng/pipelines/build-windows-job.yml
  parameters:
    jobName: Build_Windows_Debug
    testArtifactName: Transport_Artifacts_Windows_Debug
    configuration: Debug
    queueName: BuildPool.Windows.10.Amd64.Open

- template: eng/pipelines/build-windows-job.yml
  parameters:
    jobName: Build_Windows_Release
    testArtifactName: Transport_Artifacts_Windows_Release
    configuration: Release
    queueName: BuildPool.Windows.10.Amd64.Open

- template: eng/pipelines/test-windows-job.yml
  parameters:
    testRunName: 'Test Windows Desktop Debug 32'
    jobName: Test_Windows_Desktop_Debug_32
    buildJobName: Build_Windows_Debug
    testArtifactName: Transport_Artifacts_Windows_Debug
    configuration: Debug
    testArguments: -testDesktop -test32

- template: eng/pipelines/test-windows-job.yml
  parameters:
    testRunName: 'Test Windows Desktop Debug 64'
    jobName: Test_Windows_Desktop_Debug_64
    buildJobName: Build_Windows_Debug
    testArtifactName: Transport_Artifacts_Windows_Debug
    configuration: Debug
    testArguments: -testDesktop -test64

- template: eng/pipelines/test-windows-job.yml
  parameters:
    testRunName: 'Test Windows Desktop Release 32'
    jobName: Test_Windows_Desktop_Release_32
    buildJobName: Build_Windows_Release
    testArtifactName: Transport_Artifacts_Windows_Release
    configuration: Release
    testArguments: -testDesktop -test32

- template: eng/pipelines/test-windows-job.yml
  parameters:
    testRunName: 'Test Windows Desktop Spanish Release 32'
    jobName: Test_Windows_Desktop_Spanish_Release_32
    buildJobName: Build_Windows_Release
    testArtifactName: Transport_Artifacts_Windows_Release
    configuration: Release
    testArguments: -testDesktop -test32 -helixQueueName Windows.10.Amd64.Server19H1.ES.Open

- template: eng/pipelines/test-windows-job.yml
  parameters:
    testRunName: 'Test Windows Desktop Release 64'
    jobName: Test_Windows_Desktop_Release_64
    buildJobName: Build_Windows_Release
    testArtifactName: Transport_Artifacts_Windows_Release
    configuration: Release
    testArguments: -testDesktop -test64